/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IJustLendInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "borrow"
      | "claimComp"
      | "deposit"
      | "enterMarkets"
      | "exitMarket"
      | "getAccountLiquidity"
      | "redeem"
      | "redeemAll"
      | "repayBorrow"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "borrow",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimComp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterMarkets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "exitMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountLiquidity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemAll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repayBorrow",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimComp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enterMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exitMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repayBorrow",
    data: BytesLike
  ): Result;
}

export interface IJustLend extends BaseContract {
  connect(runner?: ContractRunner | null): IJustLend;
  waitForDeployment(): Promise<this>;

  interface: IJustLendInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  borrow: TypedContractMethod<
    [jToken: AddressLike, borrowAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimComp: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [jToken: AddressLike, underlyingAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  enterMarkets: TypedContractMethod<
    [jTokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  exitMarket: TypedContractMethod<[jToken: AddressLike], [void], "nonpayable">;

  getAccountLiquidity: TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { accountLiquidity: bigint; accountShortfall: bigint }],
    "view"
  >;

  redeem: TypedContractMethod<
    [jToken: AddressLike, jTokenAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  redeemAll: TypedContractMethod<[jToken: AddressLike], [bigint], "nonpayable">;

  repayBorrow: TypedContractMethod<
    [jToken: AddressLike, repayAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [jToken: AddressLike, borrowAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimComp"
  ): TypedContractMethod<[account: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [jToken: AddressLike, underlyingAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterMarkets"
  ): TypedContractMethod<[jTokens: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exitMarket"
  ): TypedContractMethod<[jToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccountLiquidity"
  ): TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { accountLiquidity: bigint; accountShortfall: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [jToken: AddressLike, jTokenAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemAll"
  ): TypedContractMethod<[jToken: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "repayBorrow"
  ): TypedContractMethod<
    [jToken: AddressLike, repayAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
