/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IUnitrollerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimComp"
      | "enterMarkets"
      | "exitMarket"
      | "getAccountLiquidity"
      | "getAssetsIn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimComp",
    values: [AddressLike[], AddressLike[], boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "enterMarkets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "exitMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountLiquidity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetsIn",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "claimComp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enterMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exitMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetsIn",
    data: BytesLike
  ): Result;
}

export interface IUnitroller extends BaseContract {
  connect(runner?: ContractRunner | null): IUnitroller;
  waitForDeployment(): Promise<this>;

  interface: IUnitrollerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimComp: TypedContractMethod<
    [
      holders: AddressLike[],
      jTokens: AddressLike[],
      borrowers: boolean,
      suppliers: boolean
    ],
    [void],
    "nonpayable"
  >;

  enterMarkets: TypedContractMethod<
    [jTokens: AddressLike[]],
    [bigint[]],
    "nonpayable"
  >;

  exitMarket: TypedContractMethod<
    [jToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getAccountLiquidity: TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { liquidity: bigint; shortfall: bigint }],
    "view"
  >;

  getAssetsIn: TypedContractMethod<[account: AddressLike], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimComp"
  ): TypedContractMethod<
    [
      holders: AddressLike[],
      jTokens: AddressLike[],
      borrowers: boolean,
      suppliers: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterMarkets"
  ): TypedContractMethod<[jTokens: AddressLike[]], [bigint[]], "nonpayable">;
  getFunction(
    nameOrSignature: "exitMarket"
  ): TypedContractMethod<[jToken: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccountLiquidity"
  ): TypedContractMethod<
    [account: AddressLike],
    [[bigint, bigint] & { liquidity: bigint; shortfall: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssetsIn"
  ): TypedContractMethod<[account: AddressLike], [string[]], "view">;

  filters: {};
}
