/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iJustLendSol from "./IJustLend.sol";
export type { iJustLendSol };
export type { ITRC20 } from "./ITRC20";
export type { TronPaymentSplitter } from "./TronPaymentSplitter";
export type { TronPaymentVault } from "./TronPaymentVault";
