/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TronPaymentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSigner"
      | "addSupportedToken"
      | "approvePayment"
      | "cancelPayment"
      | "dailyLimit"
      | "dailyPaid"
      | "emergencyRequests"
      | "executeEmergencyWithdrawal"
      | "executePayment"
      | "getBalance"
      | "getPayment"
      | "getRemainingDailyLimit"
      | "getSigners"
      | "guardian"
      | "hasApproved"
      | "isSigner"
      | "lastDailyReset"
      | "nextPaymentId"
      | "pause"
      | "paused"
      | "payments"
      | "proposePayment"
      | "removeSigner"
      | "removeSupportedToken"
      | "requestEmergencyWithdrawal"
      | "signers"
      | "supportedTokens"
      | "threshold"
      | "timelock"
      | "unpause"
      | "updateDailyLimit"
      | "updateThreshold"
      | "updateTimelock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyLimitUpdated"
      | "EmergencyWithdrawalExecuted"
      | "EmergencyWithdrawalRequested"
      | "PaymentApproved"
      | "PaymentCancelled"
      | "PaymentExecuted"
      | "PaymentProposed"
      | "SignerAdded"
      | "SignerRemoved"
      | "ThresholdUpdated"
      | "TimelockUpdated"
      | "VaultPaused"
      | "VaultUnpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dailyPaid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEmergencyWithdrawal",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "guardian", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDailyReset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposePayment",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEmergencyWithdrawal",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTimelock",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyLimit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dailyPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEmergencyWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastDailyReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEmergencyWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTimelock",
    data: BytesLike
  ): Result;
}

export namespace DailyLimitUpdatedEvent {
  export type InputTuple = [oldLimit: BigNumberish, newLimit: BigNumberish];
  export type OutputTuple = [oldLimit: bigint, newLimit: bigint];
  export interface OutputObject {
    oldLimit: bigint;
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalExecutedEvent {
  export type InputTuple = [
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [to: string, token: string, amount: bigint];
  export interface OutputObject {
    to: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalRequestedEvent {
  export type InputTuple = [
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    token: string,
    amount: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    to: string;
    token: string;
    amount: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentApprovedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    signer: AddressLike,
    approvals: BigNumberish,
    required: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    signer: string,
    approvals: bigint,
    required: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    signer: string;
    approvals: bigint;
    required: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCancelledEvent {
  export type InputTuple = [paymentId: BigNumberish];
  export type OutputTuple = [paymentId: bigint];
  export interface OutputObject {
    paymentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    txHash: BytesLike
  ];
  export type OutputTuple = [
    paymentId: bigint,
    token: string,
    to: string,
    amount: bigint,
    txHash: string
  ];
  export interface OutputObject {
    paymentId: bigint;
    token: string;
    to: string;
    amount: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProposedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike,
    proposedAt: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    token: string,
    to: string,
    amount: bigint,
    data: string,
    proposedAt: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    token: string;
    to: string;
    amount: bigint;
    data: string;
    proposedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAddedEvent {
  export type InputTuple = [signer: AddressLike, threshold: BigNumberish];
  export type OutputTuple = [signer: string, threshold: bigint];
  export interface OutputObject {
    signer: string;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerRemovedEvent {
  export type InputTuple = [signer: AddressLike, threshold: BigNumberish];
  export type OutputTuple = [signer: string, threshold: bigint];
  export interface OutputObject {
    signer: string;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockUpdatedEvent {
  export type InputTuple = [
    oldTimelock: BigNumberish,
    newTimelock: BigNumberish
  ];
  export type OutputTuple = [oldTimelock: bigint, newTimelock: bigint];
  export interface OutputObject {
    oldTimelock: bigint;
    newTimelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultPausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnpausedEvent {
  export type InputTuple = [unpauser: AddressLike];
  export type OutputTuple = [unpauser: string];
  export interface OutputObject {
    unpauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TronPaymentVault extends BaseContract {
  connect(runner?: ContractRunner | null): TronPaymentVault;
  waitForDeployment(): Promise<this>;

  interface: TronPaymentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  addSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  approvePayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  dailyLimit: TypedContractMethod<[], [bigint], "view">;

  dailyPaid: TypedContractMethod<[], [bigint], "view">;

  emergencyRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        to: string;
        token: string;
        amount: bigint;
        unlockTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  executeEmergencyWithdrawal: TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      requestTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executePayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean, boolean, bigint] & {
        token: string;
        to: string;
        amount: bigint;
        approvalCount: bigint;
        required: bigint;
        executed: boolean;
        cancelled: boolean;
        proposedAt: bigint;
      }
    ],
    "view"
  >;

  getRemainingDailyLimit: TypedContractMethod<[], [bigint], "view">;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  guardian: TypedContractMethod<[], [string], "view">;

  hasApproved: TypedContractMethod<
    [paymentId: BigNumberish, signer: AddressLike],
    [boolean],
    "view"
  >;

  isSigner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastDailyReset: TypedContractMethod<[], [bigint], "view">;

  nextPaymentId: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, bigint, boolean, boolean, bigint] & {
        token: string;
        to: string;
        amount: bigint;
        data: string;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
        proposedAt: bigint;
      }
    ],
    "view"
  >;

  proposePayment: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  removeSigner: TypedContractMethod<
    [signer: AddressLike],
    [void],
    "nonpayable"
  >;

  removeSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  requestEmergencyWithdrawal: TypedContractMethod<
    [to: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  signers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  threshold: TypedContractMethod<[], [bigint], "view">;

  timelock: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateDailyLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTimelock: TypedContractMethod<
    [newTimelock: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvePayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        to: string;
        token: string;
        amount: bigint;
        unlockTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeEmergencyWithdrawal"
  ): TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      requestTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean, boolean, bigint] & {
        token: string;
        to: string;
        amount: bigint;
        approvalCount: bigint;
        required: bigint;
        executed: boolean;
        cancelled: boolean;
        proposedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "guardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [paymentId: BigNumberish, signer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSigner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastDailyReset"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, bigint, boolean, boolean, bigint] & {
        token: string;
        to: string;
        amount: bigint;
        data: string;
        approvalCount: bigint;
        executed: boolean;
        cancelled: boolean;
        proposedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposePayment"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestEmergencyWithdrawal"
  ): TypedContractMethod<
    [to: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDailyLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTimelock"
  ): TypedContractMethod<[newTimelock: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DailyLimitUpdated"
  ): TypedContractEvent<
    DailyLimitUpdatedEvent.InputTuple,
    DailyLimitUpdatedEvent.OutputTuple,
    DailyLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawalExecuted"
  ): TypedContractEvent<
    EmergencyWithdrawalExecutedEvent.InputTuple,
    EmergencyWithdrawalExecutedEvent.OutputTuple,
    EmergencyWithdrawalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawalRequested"
  ): TypedContractEvent<
    EmergencyWithdrawalRequestedEvent.InputTuple,
    EmergencyWithdrawalRequestedEvent.OutputTuple,
    EmergencyWithdrawalRequestedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentApproved"
  ): TypedContractEvent<
    PaymentApprovedEvent.InputTuple,
    PaymentApprovedEvent.OutputTuple,
    PaymentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCancelled"
  ): TypedContractEvent<
    PaymentCancelledEvent.InputTuple,
    PaymentCancelledEvent.OutputTuple,
    PaymentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProposed"
  ): TypedContractEvent<
    PaymentProposedEvent.InputTuple,
    PaymentProposedEvent.OutputTuple,
    PaymentProposedEvent.OutputObject
  >;
  getEvent(
    key: "SignerAdded"
  ): TypedContractEvent<
    SignerAddedEvent.InputTuple,
    SignerAddedEvent.OutputTuple,
    SignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "SignerRemoved"
  ): TypedContractEvent<
    SignerRemovedEvent.InputTuple,
    SignerRemovedEvent.OutputTuple,
    SignerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockUpdated"
  ): TypedContractEvent<
    TimelockUpdatedEvent.InputTuple,
    TimelockUpdatedEvent.OutputTuple,
    TimelockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultPaused"
  ): TypedContractEvent<
    VaultPausedEvent.InputTuple,
    VaultPausedEvent.OutputTuple,
    VaultPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnpaused"
  ): TypedContractEvent<
    VaultUnpausedEvent.InputTuple,
    VaultUnpausedEvent.OutputTuple,
    VaultUnpausedEvent.OutputObject
  >;

  filters: {
    "DailyLimitUpdated(uint256,uint256)": TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;
    DailyLimitUpdated: TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;

    "EmergencyWithdrawalExecuted(address,address,uint256)": TypedContractEvent<
      EmergencyWithdrawalExecutedEvent.InputTuple,
      EmergencyWithdrawalExecutedEvent.OutputTuple,
      EmergencyWithdrawalExecutedEvent.OutputObject
    >;
    EmergencyWithdrawalExecuted: TypedContractEvent<
      EmergencyWithdrawalExecutedEvent.InputTuple,
      EmergencyWithdrawalExecutedEvent.OutputTuple,
      EmergencyWithdrawalExecutedEvent.OutputObject
    >;

    "EmergencyWithdrawalRequested(address,address,uint256,uint256)": TypedContractEvent<
      EmergencyWithdrawalRequestedEvent.InputTuple,
      EmergencyWithdrawalRequestedEvent.OutputTuple,
      EmergencyWithdrawalRequestedEvent.OutputObject
    >;
    EmergencyWithdrawalRequested: TypedContractEvent<
      EmergencyWithdrawalRequestedEvent.InputTuple,
      EmergencyWithdrawalRequestedEvent.OutputTuple,
      EmergencyWithdrawalRequestedEvent.OutputObject
    >;

    "PaymentApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      PaymentApprovedEvent.InputTuple,
      PaymentApprovedEvent.OutputTuple,
      PaymentApprovedEvent.OutputObject
    >;
    PaymentApproved: TypedContractEvent<
      PaymentApprovedEvent.InputTuple,
      PaymentApprovedEvent.OutputTuple,
      PaymentApprovedEvent.OutputObject
    >;

    "PaymentCancelled(uint256)": TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;
    PaymentCancelled: TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;

    "PaymentExecuted(uint256,address,address,uint256,bytes)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PaymentProposed(uint256,address,address,uint256,bytes,uint256)": TypedContractEvent<
      PaymentProposedEvent.InputTuple,
      PaymentProposedEvent.OutputTuple,
      PaymentProposedEvent.OutputObject
    >;
    PaymentProposed: TypedContractEvent<
      PaymentProposedEvent.InputTuple,
      PaymentProposedEvent.OutputTuple,
      PaymentProposedEvent.OutputObject
    >;

    "SignerAdded(address,uint256)": TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;
    SignerAdded: TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;

    "SignerRemoved(address,uint256)": TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;
    SignerRemoved: TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    "TimelockUpdated(uint256,uint256)": TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;
    TimelockUpdated: TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;

    "VaultPaused(address)": TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;
    VaultPaused: TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;

    "VaultUnpaused(address)": TypedContractEvent<
      VaultUnpausedEvent.InputTuple,
      VaultUnpausedEvent.OutputTuple,
      VaultUnpausedEvent.OutputObject
    >;
    VaultUnpaused: TypedContractEvent<
      VaultUnpausedEvent.InputTuple,
      VaultUnpausedEvent.OutputTuple,
      VaultUnpausedEvent.OutputObject
    >;
  };
}
