/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TronPaymentSplitter {
  export type BeneficiaryStruct = {
    account: AddressLike;
    percentage: BigNumberish;
    fixedAmount: BigNumberish;
    tier: BigNumberish;
  };

  export type BeneficiaryStructOutput = [
    account: string,
    percentage: bigint,
    fixedAmount: bigint,
    tier: bigint
  ] & {
    account: string;
    percentage: bigint;
    fixedAmount: bigint;
    tier: bigint;
  };
}

export interface TronPaymentSplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addBeneficiary"
      | "addSupportedToken"
      | "beneficiaryBalances"
      | "calculateDistribution"
      | "createSplit"
      | "executeSplit"
      | "getBeneficiaries"
      | "getSplit"
      | "getTokenBalance"
      | "isTokenSupported"
      | "nextSplitId"
      | "owner"
      | "pauseSplit"
      | "removeBeneficiary"
      | "removeSupportedToken"
      | "splits"
      | "supportedTokens"
      | "tokenBalances"
      | "unpauseSplit"
      | "updateBeneficiary"
      | "updateMinAmount"
      | "updateOwner"
      | "updateSplitMode"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryAdded"
      | "BeneficiaryRemoved"
      | "BeneficiaryUpdated"
      | "Claimed"
      | "MinAmountUpdated"
      | "SplitCreated"
      | "SplitExecuted"
      | "SplitModeUpdated"
      | "SplitPaused"
      | "SplitUnpaused"
      | "TokenWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addBeneficiary",
    values: [BigNumberish, TronPaymentSplitter.BeneficiaryStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDistribution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSplit",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      TronPaymentSplitter.BeneficiaryStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSplit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSplitId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBeneficiary",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "splits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBalances",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBeneficiary",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSplitMode",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSplit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSplitId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauseSplit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMinAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSplitMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryAddedEvent {
  export type InputTuple = [
    splitId: BigNumberish,
    beneficiary: AddressLike,
    percentage: BigNumberish,
    fixedAmount: BigNumberish
  ];
  export type OutputTuple = [
    splitId: bigint,
    beneficiary: string,
    percentage: bigint,
    fixedAmount: bigint
  ];
  export interface OutputObject {
    splitId: bigint;
    beneficiary: string;
    percentage: bigint;
    fixedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryRemovedEvent {
  export type InputTuple = [splitId: BigNumberish, beneficiary: AddressLike];
  export type OutputTuple = [splitId: bigint, beneficiary: string];
  export interface OutputObject {
    splitId: bigint;
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryUpdatedEvent {
  export type InputTuple = [
    splitId: BigNumberish,
    beneficiary: AddressLike,
    newPercentage: BigNumberish,
    newFixedAmount: BigNumberish
  ];
  export type OutputTuple = [
    splitId: bigint,
    beneficiary: string,
    newPercentage: bigint,
    newFixedAmount: bigint
  ];
  export interface OutputObject {
    splitId: bigint;
    beneficiary: string;
    newPercentage: bigint;
    newFixedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    beneficiary: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    beneficiary: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinAmountUpdatedEvent {
  export type InputTuple = [
    splitId: BigNumberish,
    oldMinAmount: BigNumberish,
    newMinAmount: BigNumberish
  ];
  export type OutputTuple = [
    splitId: bigint,
    oldMinAmount: bigint,
    newMinAmount: bigint
  ];
  export interface OutputObject {
    splitId: bigint;
    oldMinAmount: bigint;
    newMinAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitCreatedEvent {
  export type InputTuple = [
    splitId: BigNumberish,
    token: AddressLike,
    mode: BigNumberish,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    splitId: bigint,
    token: string,
    mode: bigint,
    createdAt: bigint
  ];
  export interface OutputObject {
    splitId: bigint;
    token: string;
    mode: bigint;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitExecutedEvent {
  export type InputTuple = [
    splitId: BigNumberish,
    token: AddressLike,
    totalAmount: BigNumberish,
    beneficiaryCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    splitId: bigint,
    token: string,
    totalAmount: bigint,
    beneficiaryCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    splitId: bigint;
    token: string;
    totalAmount: bigint;
    beneficiaryCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitModeUpdatedEvent {
  export type InputTuple = [
    splitId: BigNumberish,
    oldMode: BigNumberish,
    newMode: BigNumberish
  ];
  export type OutputTuple = [splitId: bigint, oldMode: bigint, newMode: bigint];
  export interface OutputObject {
    splitId: bigint;
    oldMode: bigint;
    newMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitPausedEvent {
  export type InputTuple = [splitId: BigNumberish];
  export type OutputTuple = [splitId: bigint];
  export interface OutputObject {
    splitId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitUnpausedEvent {
  export type InputTuple = [splitId: BigNumberish];
  export type OutputTuple = [splitId: bigint];
  export interface OutputObject {
    splitId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TronPaymentSplitter extends BaseContract {
  connect(runner?: ContractRunner | null): TronPaymentSplitter;
  waitForDeployment(): Promise<this>;

  interface: TronPaymentSplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBeneficiary: TypedContractMethod<
    [splitId: BigNumberish, beneficiary: TronPaymentSplitter.BeneficiaryStruct],
    [void],
    "nonpayable"
  >;

  addSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  beneficiaryBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  calculateDistribution: TypedContractMethod<
    [splitId: BigNumberish, amount: BigNumberish],
    [bigint[]],
    "view"
  >;

  createSplit: TypedContractMethod<
    [
      token: AddressLike,
      mode: BigNumberish,
      minAmount: BigNumberish,
      beneficiaries: TronPaymentSplitter.BeneficiaryStruct[]
    ],
    [bigint],
    "nonpayable"
  >;

  executeSplit: TypedContractMethod<
    [splitId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBeneficiaries: TypedContractMethod<
    [splitId: BigNumberish],
    [
      [string[], bigint[], bigint[], bigint[]] & {
        accounts: string[];
        percentages: bigint[];
        fixedAmounts: bigint[];
        tiers: bigint[];
      }
    ],
    "view"
  >;

  getSplit: TypedContractMethod<
    [splitId: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        token: string;
        mode: bigint;
        minAmount: bigint;
        paused: boolean;
        beneficiaryCount: bigint;
        createdAt: bigint;
        lastExecuted: bigint;
        totalReceived: bigint;
        totalDistributed: bigint;
      }
    ],
    "view"
  >;

  getTokenBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  isTokenSupported: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  nextSplitId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseSplit: TypedContractMethod<
    [splitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeBeneficiary: TypedContractMethod<
    [splitId: BigNumberish, beneficiaryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  removeSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  splits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint, bigint, bigint] & {
        token: string;
        mode: bigint;
        minAmount: bigint;
        paused: boolean;
        createdAt: bigint;
        lastExecuted: bigint;
        totalReceived: bigint;
        totalDistributed: bigint;
      }
    ],
    "view"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike],
    [bigint],
    "view"
  >;

  unpauseSplit: TypedContractMethod<
    [splitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateBeneficiary: TypedContractMethod<
    [
      splitId: BigNumberish,
      beneficiaryAddress: AddressLike,
      newPercentage: BigNumberish,
      newFixedAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateMinAmount: TypedContractMethod<
    [splitId: BigNumberish, newMinAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateOwner: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSplitMode: TypedContractMethod<
    [splitId: BigNumberish, newMode: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBeneficiary"
  ): TypedContractMethod<
    [splitId: BigNumberish, beneficiary: TronPaymentSplitter.BeneficiaryStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "beneficiaryBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateDistribution"
  ): TypedContractMethod<
    [splitId: BigNumberish, amount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "createSplit"
  ): TypedContractMethod<
    [
      token: AddressLike,
      mode: BigNumberish,
      minAmount: BigNumberish,
      beneficiaries: TronPaymentSplitter.BeneficiaryStruct[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSplit"
  ): TypedContractMethod<
    [splitId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaries"
  ): TypedContractMethod<
    [splitId: BigNumberish],
    [
      [string[], bigint[], bigint[], bigint[]] & {
        accounts: string[];
        percentages: bigint[];
        fixedAmounts: bigint[];
        tiers: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSplit"
  ): TypedContractMethod<
    [splitId: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        token: string;
        mode: bigint;
        minAmount: bigint;
        paused: boolean;
        beneficiaryCount: bigint;
        createdAt: bigint;
        lastExecuted: bigint;
        totalReceived: bigint;
        totalDistributed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextSplitId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseSplit"
  ): TypedContractMethod<[splitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeBeneficiary"
  ): TypedContractMethod<
    [splitId: BigNumberish, beneficiaryAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint, bigint, bigint] & {
        token: string;
        mode: bigint;
        minAmount: bigint;
        paused: boolean;
        createdAt: bigint;
        lastExecuted: bigint;
        totalReceived: bigint;
        totalDistributed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpauseSplit"
  ): TypedContractMethod<[splitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBeneficiary"
  ): TypedContractMethod<
    [
      splitId: BigNumberish,
      beneficiaryAddress: AddressLike,
      newPercentage: BigNumberish,
      newFixedAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMinAmount"
  ): TypedContractMethod<
    [splitId: BigNumberish, newMinAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateOwner"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSplitMode"
  ): TypedContractMethod<
    [splitId: BigNumberish, newMode: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BeneficiaryAdded"
  ): TypedContractEvent<
    BeneficiaryAddedEvent.InputTuple,
    BeneficiaryAddedEvent.OutputTuple,
    BeneficiaryAddedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryRemoved"
  ): TypedContractEvent<
    BeneficiaryRemovedEvent.InputTuple,
    BeneficiaryRemovedEvent.OutputTuple,
    BeneficiaryRemovedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryUpdated"
  ): TypedContractEvent<
    BeneficiaryUpdatedEvent.InputTuple,
    BeneficiaryUpdatedEvent.OutputTuple,
    BeneficiaryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MinAmountUpdated"
  ): TypedContractEvent<
    MinAmountUpdatedEvent.InputTuple,
    MinAmountUpdatedEvent.OutputTuple,
    MinAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SplitCreated"
  ): TypedContractEvent<
    SplitCreatedEvent.InputTuple,
    SplitCreatedEvent.OutputTuple,
    SplitCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SplitExecuted"
  ): TypedContractEvent<
    SplitExecutedEvent.InputTuple,
    SplitExecutedEvent.OutputTuple,
    SplitExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SplitModeUpdated"
  ): TypedContractEvent<
    SplitModeUpdatedEvent.InputTuple,
    SplitModeUpdatedEvent.OutputTuple,
    SplitModeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SplitPaused"
  ): TypedContractEvent<
    SplitPausedEvent.InputTuple,
    SplitPausedEvent.OutputTuple,
    SplitPausedEvent.OutputObject
  >;
  getEvent(
    key: "SplitUnpaused"
  ): TypedContractEvent<
    SplitUnpausedEvent.InputTuple,
    SplitUnpausedEvent.OutputTuple,
    SplitUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWithdrawn"
  ): TypedContractEvent<
    TokenWithdrawnEvent.InputTuple,
    TokenWithdrawnEvent.OutputTuple,
    TokenWithdrawnEvent.OutputObject
  >;

  filters: {
    "BeneficiaryAdded(uint256,address,uint256,uint256)": TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;
    BeneficiaryAdded: TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;

    "BeneficiaryRemoved(uint256,address)": TypedContractEvent<
      BeneficiaryRemovedEvent.InputTuple,
      BeneficiaryRemovedEvent.OutputTuple,
      BeneficiaryRemovedEvent.OutputObject
    >;
    BeneficiaryRemoved: TypedContractEvent<
      BeneficiaryRemovedEvent.InputTuple,
      BeneficiaryRemovedEvent.OutputTuple,
      BeneficiaryRemovedEvent.OutputObject
    >;

    "BeneficiaryUpdated(uint256,address,uint256,uint256)": TypedContractEvent<
      BeneficiaryUpdatedEvent.InputTuple,
      BeneficiaryUpdatedEvent.OutputTuple,
      BeneficiaryUpdatedEvent.OutputObject
    >;
    BeneficiaryUpdated: TypedContractEvent<
      BeneficiaryUpdatedEvent.InputTuple,
      BeneficiaryUpdatedEvent.OutputTuple,
      BeneficiaryUpdatedEvent.OutputObject
    >;

    "Claimed(address,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "MinAmountUpdated(uint256,uint256,uint256)": TypedContractEvent<
      MinAmountUpdatedEvent.InputTuple,
      MinAmountUpdatedEvent.OutputTuple,
      MinAmountUpdatedEvent.OutputObject
    >;
    MinAmountUpdated: TypedContractEvent<
      MinAmountUpdatedEvent.InputTuple,
      MinAmountUpdatedEvent.OutputTuple,
      MinAmountUpdatedEvent.OutputObject
    >;

    "SplitCreated(uint256,address,uint8,uint256)": TypedContractEvent<
      SplitCreatedEvent.InputTuple,
      SplitCreatedEvent.OutputTuple,
      SplitCreatedEvent.OutputObject
    >;
    SplitCreated: TypedContractEvent<
      SplitCreatedEvent.InputTuple,
      SplitCreatedEvent.OutputTuple,
      SplitCreatedEvent.OutputObject
    >;

    "SplitExecuted(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      SplitExecutedEvent.InputTuple,
      SplitExecutedEvent.OutputTuple,
      SplitExecutedEvent.OutputObject
    >;
    SplitExecuted: TypedContractEvent<
      SplitExecutedEvent.InputTuple,
      SplitExecutedEvent.OutputTuple,
      SplitExecutedEvent.OutputObject
    >;

    "SplitModeUpdated(uint256,uint8,uint8)": TypedContractEvent<
      SplitModeUpdatedEvent.InputTuple,
      SplitModeUpdatedEvent.OutputTuple,
      SplitModeUpdatedEvent.OutputObject
    >;
    SplitModeUpdated: TypedContractEvent<
      SplitModeUpdatedEvent.InputTuple,
      SplitModeUpdatedEvent.OutputTuple,
      SplitModeUpdatedEvent.OutputObject
    >;

    "SplitPaused(uint256)": TypedContractEvent<
      SplitPausedEvent.InputTuple,
      SplitPausedEvent.OutputTuple,
      SplitPausedEvent.OutputObject
    >;
    SplitPaused: TypedContractEvent<
      SplitPausedEvent.InputTuple,
      SplitPausedEvent.OutputTuple,
      SplitPausedEvent.OutputObject
    >;

    "SplitUnpaused(uint256)": TypedContractEvent<
      SplitUnpausedEvent.InputTuple,
      SplitUnpausedEvent.OutputTuple,
      SplitUnpausedEvent.OutputObject
    >;
    SplitUnpaused: TypedContractEvent<
      SplitUnpausedEvent.InputTuple,
      SplitUnpausedEvent.OutputTuple,
      SplitUnpausedEvent.OutputObject
    >;

    "TokenWithdrawn(address,address,uint256)": TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
    TokenWithdrawn: TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
  };
}
