/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJustLendPriceOracle,
  IJustLendPriceOracleInterface,
} from "../../../../contracts/tron/IJustLend.sol/IJustLendPriceOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "jToken",
        type: "address",
      },
    ],
    name: "getUnderlyingPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IJustLendPriceOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IJustLendPriceOracleInterface {
    return new Interface(_abi) as IJustLendPriceOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJustLendPriceOracle {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IJustLendPriceOracle;
  }
}
